HashTest:
	g++ HashTest.cpp Hash.cpp -o hashtest -I /usr/include/openssl/ -l ssl -lcrypto

RsaTest:
	g++ RsaTest.cpp -o rsatest -I /usr/include/openssl/ -l ssl -lcrypto

MyRsa:
	g++ MyRsa.cpp RsaTest.cpp -o rsatest -I /usr/include/openssl/ -l ssl -lcrypto

Aes:
	g++ RsaTest.cpp -o rsatest -I /usr/include/openssl/ -l ssl -lcrypto