seckey:
	g++ EencTest.cpp Code.cpp CodecFactoryBase.cpp RequestCodec.cpp \
	RequestCodecFactory.cpp RequestMsg.pb.cc RespoenseCodec.cpp \
	ResponseCodecFactory.cpp ResponseMsg.pb.cc -o test `pkg-config --libs --cflags protobuf` 