testBaseShm1:
	g++ BaseShm.cpp test.cpp -o test

testBaseShm2:
	g++ BaseShm.cpp test.cpp -o test2 

testSecKeyShm3:
	g++ BaseShm.cpp test.cpp SecKeyShm.cpp -o test3

testSecKeyShm4:
	g++ BaseShm.cpp test.cpp SecKeyShm.cpp -o test4